export enum OrderStatus {
    PAID = 'PAID',
    UNPAID = 'UNPAID',
    PENDING = 'PENDING',
    PROCESSING = 'PROCESSING',
    SHIPPED = 'SHIPPED',
    DELIVERED = 'DELIVERED',
    CANCELLED = 'CANCELLED',
}